### ISSUE TITLE
[🗃]: Some Missing Things I found

### ISSUE THREAD

**Issue by Derpgamer22** [MehVahdJukaar/WoodGood#495]
### Version

Wood Works 2.2.2

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/woodworks

### Details

It is the same thing pretty much... architect's palette twisted wood doesn't have a board type for woodworks
I am aware this is the 3rd time I have put this here and I am sorry for doing it.. I only did it as I realized that there is the Module label which I forgot to put down and I cannot figure out how to put it there :P
But anyway there is no twisted board still.. sorry again for having another duplicate.. I am not trying to be annoying

**Comment by Derpgamer22** [comment]
I just found out that I managed to find another missing item.. A hollowed log variant of the azalea log from caverns and chasms for quarks hollowed logs

**Comment by Xelbayria** [comment]
VERSION: 1.19.2

i'll investigate this.

**Comment by Derpgamer22** [comment]
yeah thanks I didn't even realize that lol until I talking about the other thing at the start and I was like.. OH.. There isn't this either??

**Comment by Derpgamer22** [comment]
whoops.. didnt mean to close it... anyway
i wanted to mention that.. still 1.19.2.. the endergetic expansion mods hollowed poise stem... or i guess it calls it a log in EC.. doesnt have the correct texture in the inside.. same for gardens of the dead's soulblight stem.. probs as they are most likely named differently..

**Comment by MehVahdJukaar** [comment]
should prbably get  custom translation string too

**Comment by Xelbayria** [comment]
alright, I'll add the custom translation string.

**Comment by Xelbayria** [comment]
> whoops.. didnt mean to close it... anyway i wanted to mention that.. still 1.19.2.. the endergetic expansion mods hollowed poise stem... or i guess it calls it a log in EC.. doesnt have the correct texture in the inside.. same for gardens of the dead's soulblight stem.. probs as they are most likely named differently..

they have texture problems, right? with woodworks?  Can you clarify above ☝️ so i can fix the problems but first, i need to understand what's the problem. 

I'm looking in the problem with "no twisted board". I have a good idea why. just testing the solution I applied to the code.

**Comment by Derpgamer22** [comment]
I actually used kubejs to fix it myself lol but i think what it is is that they use the name stem in their names... AND the stripped can be in a different location
I will put down what their textures are for you

**Comment by Derpgamer22** [comment]
![stripped_soulblight_stem](https://github.com/MehVahdJukaar/WoodGood/assets/147771102/8fe3b340-be2f-45fc-a9f4-81741157ae4e)
![poise_stem_stripped](https://github.com/MehVahdJukaar/WoodGood/assets/147771102/44c1fdde-7ba6-4381-9086-38b5c3474572)


these are the stripped textures... which are the problem

**Comment by Derpgamer22** [comment]
the poise stem is called "poise_stem_stripped"
the soulblight stem is called "stripped_soulblight_stem"

**Comment by Derpgamer22** [comment]
So pretty much they use stem instead of log AND one has stripped on a different location of the name

**Comment by Xelbayria** [comment]
I see! that's very helpful information. Thanks for the details. 

### TASKS:

- [x] fix the naming via en_us
    - [x] poise_stem
    - [x] twisted_log - FIXED & **cancelled**
    - [x] soulblight_stem
- [x] twisted stem (architect's palette) has the missing _twisted_board_ (woodworks) - should have existed, tho
- [x] azalea log (caverns and chasms) has the missing _hollowed_log_ (Quark)
- [x] texture ID of stripped_log for poise_stem: `poise_stem_stripped` 
- [x] Texture ID of _stripped_soulblight_stem_ is called `stripped_soulblight_stem`


Anything else I missed?

**Comment by Derpgamer22** [comment]
Oh btw the twisted LOG is what it is.. :p... It isn't a stem for the twisted wood stuff btw

**Comment by Xelbayria** [comment]
gotcha

**Comment by Derpgamer22** [comment]
i also found that the current verison of aether redux.. another hollow log thing for the 
jellyshroom and cloudcap

**Comment by Derpgamer22** [comment]
if u need the names I'll give them to you in a few minutes.. as imma fix the texture myself with resource packs lol

**Comment by Derpgamer22** [comment]
okay so they use the stem word.. and the stripped is at the back.. however the file is named like this at the start
block/natural/stripped_
so it has natural after the block and THEN the name of it.. (that is why the stripped is there.. so u can see when the name starts

**Comment by Derpgamer22** [comment]
I also figured out that the jelly shroom doesnt even have a stripped variant.. hm

**Comment by Xelbayria** [comment]
I discovered a bug with Moonlight/EC. the stripped_log for "stem" is not detected and added to the list. That's why These blocks are missing the stripped_log texture. I am quite surprised by this discovery.  Macaw's Furniture has plenty of stripped blocks. but not one of them is generated using stem. 

not good, tho. I told MehVahdJukaar about this and he is investigating to find out what's the problem. I'm not sure where is the cause. 

it's fine that you can fix the texture problem. but I recommend you use model files to override these model files that are using stripped_oak_log texture with the correct texture. 

Whistlecane from **gardens of the dead** doesn't have stripped_log, either. but I added the code to make the hollow log use the normal texture of the log.

**Comment by Xelbayria** [comment]
@Derpgamer22 
try to update **Moonlight lib** and check if the problem is solved or not.

**Comment by Xelbayria** [comment]
@Derpgamer22 
The translation fix is included in v2.5.22 for **1.19.2**, but the stripped_log stuff hasn't been solved yet.

**Comment by Xelbayria** [comment]
- [x] twisted stem (architect's palette) has the missing twisted_board (woodworks) - should have existed, tho
- [x] azalea log (caverns and chasms) has the missing hollowed_log (Quark)
- [x] cloudcap (aether redux)
- [x] jellyshroom (aether redux) - Canceled blc it has no stripped_stem

I'll be closing this and will try again to find out what's the problem with ☝️. 

related to #277 & original: #464

**Comment by Xelbayria** [comment]
Good news: 

> architect's palette twisted wood doesn't have a board type for woodworks

is fixed and will be in **v2.5.23**

## UPDATE:
<strike> **Aether Redux ** has a bug for _cloudcap_stem_, so _stripped_cloudcap_stem_ is using the same id as `aether_redux:cloudcap_stem`. This should be report to the dev, so the fix will be applied. </strike>

EDIT: Ignore the strike sentence, there's nothing wrong. 🤦 playing a trick on my mind. 

for now i'll apply the fix to cloudcap with the correct texture for _stripped_cloudcap_stem_

and Hollow_log for jellyshroom will be skipped because it has no stripped_stem. 

## UPDATE 2: 

**Caverns & Chasms**'s AZALEA has no stripped_log which is required because the `hollow_log` need two textures from `log` and `stripped_log`. unfortunately, it will be skipped.
