### ISSUE TITLE
[🐞]: Issue with Extended Mushrooms, missing textures for Mushroom Stems

### ISSUE THREAD

**Issue by Ghastly13** [MehVahdJukaar/WoodGood#545]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.64

### Moonlight Lib Version

2.12.6

### Issue with mods

Extended Mushrooms 4.1.3.1

### Issue Detail

Extended Mushrooms causes the Mushroom Stem block to be seen as a log, and it includes a new variant of the Mushroom Stem block called the Poisonous Mushroom Stem that do not have the correct textures for some items including Hollow Logs from Quark and the Twilight Forest and the Wired Fence from Macaw's Fences and Walls.

### OPTIONAL: To Produce

Use Extended Mushrooms with Every Compat along with Quark, The Twilight Forest, or Macaw's Fences and Walls.

**Comment by Ghastly13** [comment]
My apologies, Mushrooms Extended also adds a Glowshroom Stem and a Honey Fungus Stem with the same issue.

**Comment by Xelbayria** [comment]
I've took a look at the 5 mods. I can see the problems you speak of. 

## TASK: 

- Hollow Logs (Quark) - Also applied to **The Twilight Forest**
	- Extended Mushroom
		- [x] Glowshroom Stem
		- [x] Honey Fungus
		- [x] Mushroom
		- [x] Poisonous Mushroom
- Hedges (Macaw's Fences & Walls)
	- The Twilight Forest	
		- [x] canopy
		- [x] dark
		- [x] mangrove
		- [x] twilight oak
		- [x] beanstalk
		- [x] thorn
		- [x] rainbow oak
- Wired Fences (Macaw's Fences & Walls)
	- Extended Mushroom
		- [x] Honey Fungus
		- [x] Mushroom
		- [x] Poisonous Mushroom
		- [x] Glowshroom

- Correct the title being display with "stem" instead of "log"
	- [x] Honey Fungus
	- [x] Mushroom
	- [x] Poisonous Mushroom
	- [x] Glowshroom

**Comment by Xelbayria** [comment]
will be in **v2.6.65**
